grpc:
  server:
    port: 9898
  client:
    service-server:
      address: 'discovery:///service-server'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

server:
  port: 8080

spring:
  application:
    name: service-server
  config:
    import: optional:consul:localhost:8500
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        default-context: application
        profile-separator: ','
        data-key: data
        format: yaml
      discovery:
        health-check-interval: 10s
        health-check-critical-timeout: 5s
        health-check-url: localhost:${server.port}/actuator/health
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8858
      datasource:
        ds1:
          consul:
            host: localhost
            port: 8500
            data-type: json
            rule-type: flow
            rule-key: sentinel-rules
  security:
    user:
      name: ${helltractor.security.name}
      password: ${helltractor.security.password}
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${helltractor.datasource.host}:${helltractor.datasource.port}/${helltractor.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${helltractor.datasource.username}
    password: ${helltractor.datasource.password}
    driver-class-name: ${helltractor.datasource.driver-class-name}
  data:
    redis:
      host: ${helltractor.data.redis.host}
      port: ${helltractor.data.redis.port}
      password: ${helltractor.data.redis.password}
      database: ${helltractor.data.redis.database}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true

casbin:
  storeType: file

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      diskSpace:
        # we can disable health check, default is enable
        enabled: false
      # sentinel:
      #  enabled: false

helltractor:
  jwt:
    secret-key: mall
    ttl: 7200000
    token-name: token