grpc:
  server:
    port: 9898

server:
  port: 8080

spring:
  application:
    name: imitation-douyin-mall

  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        register: true
        hostname: localhost
        port: 8500

    sentinel:
      block-page: /errorPage
      enabled: true # 自动化配置是否生效
      eager: true   # 禁用控制台懒加载
      transport:
        dashboard: localhost:8120 # 控制台地址
#      datasource:
#        ds1:
#          consul:
#            host: localhost
#            port: 8500
#            data-id: flowrule.json
#            data-type: json
#            rule-type: flow

  profiles:
    active: dev

#  datasource:
#    druid:
#      driver-class-name: ${helltractor.datasource.driver-class-name}
#      url: jdbc:mysql://${helltractor.datasource.host}:${helltractor.datasource.port}/${helltractor.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: ${helltractor.datasource.username}
#      password: ${helltractor.datasource.password}
#      connection-timeout: ${helltractor.datasource.timeout}
#      validation-timeout: ${helltractor.datasource.timeout}
#      max-lifetime: ${helltractor.datasource.lifetime}
#      maximum-pool-size: ${helltractor.datasource.pool.max}
#      minimum-idle: ${helltractor.datasource.pool.idle}

#  redis:
#    host: ${helltractor.redis.host}
#    port: ${helltractor.redis.port}
#    password: ${helltractor.redis.password}
#    database: ${helltractor.redis.database}

#mybatis:
#    mapper-locations: classpath:mapper/*.xml
#    type-aliases-package: com.helltractor.entity
#    configuration:
#        map-underscore-to-camel-case: true

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

management:
  endpoint:
    web:
      exposure:
        include: "health,info"
    health:
      show-details: always
      diskSpace:
        # we can disable health check, default is enable
        enabled: false
      # sentinel:
      #  enabled: false